### PR TITLE
Added support for npm file map

### LINKED ISSUE #6: Integrate npm auto-update
[Bountysource](https://www.bountysource.com/issues/24609170-integrate-npm-auto-update?utm_source=24609170&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Integrate npm auto-update in, and drop the old one in cdnjs/cdnjs:
https://github.com/cdnjs/cdnjs/blob/master/auto-update.js

So the old config:
```js
  "npmName": "jquery",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/*"
      ]
    }
  ],
```

should be : 
```js
  "autoupdate": {
    "source": "npm",
    "target": "jquery",
    "fileMap": [
      {
        "basePath": "dist",
        "files": [
          "**/*"
        ]
      }
    ]
  }
```

Note that the `package.json`s, corresponding document and test should also be updated.

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fixes #6. :rocket:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@IonicaBizau do you also started the depreciation work on https://github.com/cdnjs/cdnjs/blob/master/auto-update.js and the migration PR? We'll need to test with those changes.

**Comment by PeterDaveHello** [comment]
BTW, did you just rewrite your own npm updater? I thought many parts of it can be just copied from the old one.

**Comment by IonicaBizau** [comment]
@PeterDaveHello I did copy and updated most of the code from that file. It doesn't happen often, but this time that was helpful. :grin:

**Comment by IonicaBizau** [comment]
In general, in such cases it's just easier to build things from scratch.

**Comment by IonicaBizau** [comment]
I'm working on the `cdnjs/cdnjs` scripts now.

**Comment by PeterDaveHello** [comment]
@IonicaBizau Yeah, I totally understand, just asking :)

**Comment by PeterDaveHello** [comment]
but sometimes a rewrite might miss something that we won't notice immediately, and as we don't have "tests" on that, I'll be more careful on that.

**Comment by IonicaBizau** [comment]
Indeed!

**Comment by IonicaBizau** [comment]
@PeterDaveHello Any progress on this?

**Comment by PeterDaveHello** [comment]
Sorry for the late reply @IonicaBizau, I think we are waiting for https://github.com/cdnjs/cdnjs/pull/10080?

**Comment by IonicaBizau** [comment]
Yeah, I'm traveling in India these weeks and the internet is terrible here.

Maybe I can connect to my home computer to clone the repo and solve the conflicts.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Tried, but I don't have enough space on my home computer disk... 😭 Can you solve the conflicts?

**Comment by PeterDaveHello** [comment]
@IonicaBizau maybe I'll support you a temporarily working space, let's talk in private.

**Comment by IonicaBizau** [comment]
@PeterDaveHello I'd like to finish this and merge it.

**Comment by IonicaBizau** [comment]
@PeterDaveHello What's the progress on this?

**Comment by MattIPv4** [comment]
Not sure how involved, if at all, Peter is now. This might be useful for @xtuc though, who is working on the autoupdate logic for cdnjs.

**Comment by xtuc** [comment]
As @PeterDaveHello pointed out. We currently use https://github.com/cdnjs/cdnjs/blob/master/auto-update.js to update npm packages. I'm not sure how I can help here. @IonicaBizau are you on the cdnjs slack?

**Comment by MattIPv4** [comment]
I think the aim of this PR to move away from using the cdnjs/auto-update.js file to centralize all the auto-updating in this repo, using the same auto-update config style in package.json for both npm & git.

**Comment by xtuc** [comment]
@MattIPv4 that would be great! I has been thinking of rewriting the bot/autoupdate scripts myself too, especially to remove bash scripts and hard to maintain JS.

**Comment by MattIPv4** [comment]
https://github.com/cdnjs/cdnjs/pull/10080 is the other half of this PR, which updates all the cdnjs/cdnjs package.json files to the new format this PR uses etc.

**Comment by xtuc** [comment]
Thanks for your work @IonicaBizau

**Comment by IonicaBizau** [comment]
@xtuc Is there any reason why I was removed from the organization?

I did not receive any notice or any _red flag_ before that. Have I done anything wrong?

**Comment by MattIPv4** [comment]
Hey @IonicaBizau we were doing some org cleanup. If you’re planning to continue to actively contribute to cdnjs, we can add you back :)

**Comment by IonicaBizau** [comment]
@MattIPv4 I am quite busy, but I would also like to help when I have some free time.

In the past, my notable contribution was the [`cdnjs-importer`](https://github.com/cdnjs/cdnjs-importer) — I am unsure if that still works or not.

**Comment by MattIPv4** [comment]
Hi @IonicaBizau, we are always welcoming of contributions and will continue to be! Thanks for everything you've done so far! However, with that in mind, I think the aim, for now, is to keep direct org members limited with a focus on security as Cloudflare continues to assist with cdnjs.

**Pull request merged**
